basePath: /v1
definitions:
  db.UserModel:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      passowrd:
        $ref: '#/definitions/db.password'
      updated_at:
        type: string
      username:
        type: string
    type: object
  db.password:
    type: object
  main.UserAuthenticate:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/user:
    post:
      consumes:
      - application/json
      description: create user and invitation
      parameters:
      - description: User authentication payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.UserAuthenticate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: create user and invitation
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: get user by id, id should send in params
      parameters:
      - description: userID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.UserModel'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: get user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
